api_key: "Replace with your key"
api_base: "Replace with your base url"
model: gpt-4-turbo
temperature: 0
toolbench_url: http://8.130.32.149:8080/rapidapi
tools_folder: "./tools"
cache_folder: "./tool_response_cache"
is_save: true
port: 8080
log_file: "./server.log"