### model
model_name_or_path: models/qwen2.5-3B-virtualized-2@2
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: LLaMA-Factory/examples/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: toolscaler_retrieval
dataset_dir: data
template: qwen
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: models/qwen2.5-full/sft/toolscaler_ret-2@2
logging_steps: 500
save_steps: 500
plot_loss: true
# overwrite_output_dir: true
load_best_model_at_end: true

### train
per_device_train_batch_size: 12
gradient_accumulation_steps: 8
learning_rate: 4.0e-5
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 12
eval_strategy: steps
eval_steps: 500
evaluation_strategy: steps 

report_to: none