### model
model_name_or_path: models/llama-3-8b-numeric-virtualized
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: LLaMA-Factory/examples/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: toolgen_numeric_retrieval
dataset_dir: data
template: llama3
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: models/numeric_ret
logging_steps: 10
save_steps: 10
plot_loss: true
overwrite_output_dir: true
load_best_model_at_end: true

### train
per_device_train_batch_size: 24
gradient_accumulation_steps: 8
learning_rate: 4.0e-5
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 24
eval_strategy: steps
eval_steps: 10
evaluation_strategy: steps 